name: sygeq
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  qr_code_scanner: ^1.0.1
  geolocator: ^9.0.1
  geocoding: ^2.0.4
  intl: ^0.18.1
  shared_preferences: ^2.0.15
  http: ^1.0.0
  jwt_decode: ^0.3.1
  dropdown_search: ^5.0.6
  latlong_to_osgrid: ^1.3.2
  platform_info: ^3.2.0
  pull_to_refresh: ^2.0.0
  path_provider: ^2.0.11
  device_info_plus: ^9.1.2
  flutter_launcher_icons: ^0.9.0
  fluttertoast: ^8.0.9
  connectivity_plus: ^6.1.3
  google_fonts: ^5.1.0
  syncfusion_flutter_datagrid: ^29.1.35
  flutter_document_picker: ^5.2.3
  url_launcher: ^6.1.14
  image_picker: ^0.8.3+1
  loading_animation_widget: ^1.2.0+4
  provider: ^6.0.5
  syncfusion_flutter_core: ^29.1.35
  animated_text_kit: ^4.2.2
  flutter_speed_dial: ^7.0.0
  dio: ^5.4.3+1
  font_awesome_flutter: ^10.7.0
  syncfusion_flutter_charts: ^29.1.35

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/Images/
    - assets/icons/
